### ISSUE TITLE
Tests groupe 4

### ISSUE THREAD

**Issue by MurielSM** [IFATech-Metz/dev-log-6#41]
Si on  indique la ville, coche toutes les informations et que l'on prend la météo à 5 jours, la température ne s'affiche pas. La recherche d'une deuxième ville ne se fait pas toujours et les cases cochées se réinitialisent.

**Comment by quenfil** [comment]
Il faut appuyer sur Entrée pour valider la saisie et lancer la recherche, le projet sera actualisé sous peu pour clarifier ce point auprès de l'utilisateur.
La réinitialisation des cases cochées est voulue.

Merci pour ce retour constructif.
