### ISSUE TITLE
bon projet

### ISSUE THREAD

**Issue by nico57000** [IFATech-Metz/dev-log-6#42]
Joli travail tout fonctionne très bien,
Comme indiqué dans le readme la gestion des érreurs est en cours d'implémentation.
Le responsive laisse à désirer.
J'aurais aussi précisé à l'utilisateur qu'il faut cliquer sur entrer pour valider sa requete.
Si non top

**Comment by quenfil** [comment]
Merci pour ce retour, le projet a été mis à jour à l'instant.
